### ISSUE TITLE
Unsuscribe user

### ISSUE THREAD

**Issue by pilarargudo** [GeeksHubsAcademy/bootcamp-stream-platform#16]
- [x] endpoint delete user
- [x] endpoint bootcamp unsuscribe
- [x] improve UI
- [x] modal confirm component
- [x] delete user in DB
- [x] delete profile student
- [x] delete profile admin (different endpoint)
- [x] button unsuscribe bootcamp from mybootcamp view
- [ ] button unsuscribe bootcamp action

**Comment by DavidPinilla1** [comment]
El endpoint es http://localhost:3001/bootcamp/unsuscribe/:id
el id es el del bootcamp del que el usuario se quiere desuscribir, devuelve como respuesta el bootcamp actualizado y un mensaje "You have been sucessfully unsuscribed".

**Comment by pilarargudo** [comment]
Entonces te das de baja de un bootcamp, no borramos el usuario, ¿verdad? Habrá que valorar qué pasa cuando pertenece a varios bootcamps @DavidPinilla1 y mejorar la UI.

**Comment by DavidPinilla1** [comment]
Estas en lo cierto, por ahora hoy voy a tratar de tener el backend básico listo y Juan va a conectarlo con el front-end, más adelante habrá que hacer lo que dices para darle opción al usuario de que bootcamp desea aplicar la bajar

**Comment by DavidPinilla1** [comment]
Juan ha comentado que el usuario no tiene derecho a desuscribirse del bootcamp,  únicamente puede darse de baja (es decir borrar su cuenta).

**Comment by pilarargudo** [comment]
Ok, borrado todo lo referente a desuscribirse de un bootcamp.
Si se quiere retomar más adelante, se corresponde con el commit b63e96692ca3c17fb277d56b6fb4635108320bcd
